nano:
  nano-api: https://natrium.herokuapp.com/
  nano-api-key: key
  baidu-translation-app-id:
  baidu-translation-secret-key:
  bot-list:
    - name: nano
      username: nano_telegram_bot
      token: token
    - name: nano-000
      username: nano_000_bot
      token: token
    - name: nano-026
      username: nano_026_bot
      token: token
    - name: nano-063
      username: nano_063_bot
      token: token
    - name: nano-100
      username: nano_100_bot
      token: token
    - name: nano-233
      username: nano_233_bot
      token: token
    - name: nano-262
      username: nano_262_bot
      token: token

