spring:
  application:
    name: nano-web
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
  profiles:
    include: nano
  rabbitmq:
    addresses: ${CLOUDAMQP_URL:?}
