server:
  compression:
    enabled: true
spring:
  application:
    name: nano-web
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
    hikari:
      maximum-pool-size: 8
  profiles:
    include: nano
    active: dev
  rabbitmq:
    addresses: ${CLOUDAMQP_URL:}
